Repository hangillee/liferary-backend, pull requests merged in 2023-02, with the labels that each got.

#1 feat: implement comment and reply CRUD
  src/main/java/gdsc/skhu/liferary/controller/CommentController.java
  src/main/java/gdsc/skhu/liferary/domain/Comment.java
  src/main/java/gdsc/skhu/liferary/domain/DTO/CommentDTO.java
  src/main/java/gdsc/skhu/liferary/domain/DTO/MainPostDTO.java
  src/main/java/gdsc/skhu/liferary/repository/CommentRepository.java
  src/main/java/gdsc/skhu/liferary/service/BoardPostService.java
  src/main/java/gdsc/skhu/liferary/service/CommentService.java
Labels: enhancement

#2 Code Merge
  build.gradle
  src/main/java/gdsc/skhu/liferary/configure/SecurityConfig.java
  src/main/java/gdsc/skhu/liferary/configure/WebConfig.java
  src/main/java/gdsc/skhu/liferary/controller/MemberController.java
  src/main/java/gdsc/skhu/liferary/domain/DTO/LoginDTO.java
  src/main/java/gdsc/skhu/liferary/domain/DTO/SignUpDTO.java
  src/main/java/gdsc/skhu/liferary/domain/DTO/TokenDTO.java
  src/main/java/gdsc/skhu/liferary/domain/Member.java
  src/main/java/gdsc/skhu/liferary/jwt/JwtFilter.java
  src/main/java/gdsc/skhu/liferary/jwt/TokenProvider.java
  src/main/java/gdsc/skhu/liferary/repository/MemberRepository.java
  src/main/java/gdsc/skhu/liferary/service/JwtUserDetailsService.java
  src/main/java/gdsc/skhu/liferary/service/MemberService.java
  src/test/java/gdsc/skhu/liferary/repository/MemberRepositoryTest.java
Labels: enhancement

#3 feat: implement Google OAuth2 login
  .DS_Store
  .gitignore
  build.gradle
  src/main/java/gdsc/skhu/liferary/configure/SecurityConfig.java
  src/main/java/gdsc/skhu/liferary/configure/WebConfig.java
  src/main/java/gdsc/skhu/liferary/controller/OAuth2Controller.java
  src/main/java/gdsc/skhu/liferary/handler/OAuth2SuccessHandler.java
  src/main/java/gdsc/skhu/liferary/jwt/TokenProvider.java
  src/main/java/gdsc/skhu/liferary/service/MemberService.java
  src/main/java/gdsc/skhu/liferary/service/Oauth2MemberSerivce.java
Labels: enhancement

#5 feat: implement Google OAuth2 login
  .DS_Store
  .gitignore
  build.gradle
  src/main/java/gdsc/skhu/liferary/configure/SecurityConfig.java
  src/main/java/gdsc/skhu/liferary/configure/WebConfig.java
  src/main/java/gdsc/skhu/liferary/controller/OAuth2Controller.java
  src/main/java/gdsc/skhu/liferary/handler/OAuth2SuccessHandler.java
  src/main/java/gdsc/skhu/liferary/jwt/TokenProvider.java
  src/main/java/gdsc/skhu/liferary/service/MemberService.java
  src/main/java/gdsc/skhu/liferary/service/Oauth2MemberSerivce.java
Labels: enhancement

#6 chore: edit security config
  src/main/java/gdsc/skhu/liferary/configure/SecurityConfig.java
Labels: chore

#7 chore: edit CORS config
  src/main/java/gdsc/skhu/liferary/configure/WebConfig.java
Labels: chore

#8 chore: edit spring security config for CORS
  src/main/java/gdsc/skhu/liferary/configure/SecurityConfig.java
Labels: chore

#9 chore: edit config classes for CORS
  src/main/java/gdsc/skhu/liferary/configure/SecurityConfig.java
  src/main/java/gdsc/skhu/liferary/configure/WebConfig.java
Labels: chore

#10 chore: edit cors config
  src/main/java/gdsc/skhu/liferary/configure/SecurityConfig.java
Labels: chore

#11 chore: edit cors configure
  src/main/java/gdsc/skhu/liferary/configure/SecurityConfig.java
  src/main/java/gdsc/skhu/liferary/configure/SwaggerConfig.java
  src/main/java/gdsc/skhu/liferary/controller/OAuth2Controller.java
Labels: chore

#12 chore: test for CRUD
  src/main/java/gdsc/skhu/liferary/configure/SecurityConfig.java
Labels: chore

#13 feat: implement Firebase login
  src/main/java/gdsc/skhu/liferary/configure/FirebaseConfig.java
  src/main/java/gdsc/skhu/liferary/configure/SecurityConfig.java
  src/main/java/gdsc/skhu/liferary/controller/FirebaseController.java
  src/main/java/gdsc/skhu/liferary/controller/MainPostController.java
  src/main/java/gdsc/skhu/liferary/controller/MemberController.java
  src/main/java/gdsc/skhu/liferary/domain/DTO/OAuth2Attribute.java
  src/main/java/gdsc/skhu/liferary/service/MainPostService.java
  src/main/java/gdsc/skhu/liferary/service/MemberService.java
  src/main/java/gdsc/skhu/liferary/service/Oauth2MemberSerivce.java
  src/main/java/gdsc/skhu/liferary/service/TokenUserDetailsService.java
  src/main/java/gdsc/skhu/liferary/token/FirebaseFilter.java
  src/main/java/gdsc/skhu/liferary/token/JwtFilter.java
  src/main/java/gdsc/skhu/liferary/token/TokenProvider.java
Labels: enhancement

#14 fix: edit firebase config and refactoring codes
  src/main/java/gdsc/skhu/liferary/configure/FirebaseConfig.java
  src/main/java/gdsc/skhu/liferary/configure/SecurityConfig.java
  src/main/java/gdsc/skhu/liferary/configure/SecurityUtil.java
  src/main/java/gdsc/skhu/liferary/service/MemberService.java
  src/main/java/gdsc/skhu/liferary/service/TokenUserDetailsService.java
  src/main/resources/application.yml
Labels: fix

#15 chore: test code
  src/main/java/gdsc/skhu/liferary/configure/FirebaseConfig.java
Labels: chore

#16 fix: fix Firebase authentication logics
  src/main/java/gdsc/skhu/liferary/configure/SecurityConfig.java
  src/main/java/gdsc/skhu/liferary/controller/FirebaseController.java
  src/main/java/gdsc/skhu/liferary/service/MemberService.java
  src/main/java/gdsc/skhu/liferary/service/TokenUserDetailsService.java
  src/main/java/gdsc/skhu/liferary/token/FirebaseFilter.java
  src/main/java/gdsc/skhu/liferary/token/JwtFilter.java
  src/main/java/gdsc/skhu/liferary/token/TokenProvider.java
Labels: fix

#17 fix: fix Firebase filter error
  src/main/java/gdsc/skhu/liferary/configure/FirebaseConfig.java
  src/main/java/gdsc/skhu/liferary/configure/SecurityConfig.java
  src/main/java/gdsc/skhu/liferary/service/MainPostService.java
  src/main/java/gdsc/skhu/liferary/token/FirebaseFilter.java
  src/main/java/gdsc/skhu/liferary/token/TokenProvider.java
Labels: fix

#18 feat: implemet file uploading with Firebase Storage
  src/main/java/gdsc/skhu/liferary/configure/FirebaseConfig.java
  src/main/java/gdsc/skhu/liferary/controller/BoardPostController.java
  src/main/java/gdsc/skhu/liferary/controller/MainPostController.java
  src/main/java/gdsc/skhu/liferary/domain/BoardPost.java
  src/main/java/gdsc/skhu/liferary/domain/DTO/BoardPostDTO.java
  src/main/java/gdsc/skhu/liferary/domain/DTO/ImageDTO.java
  src/main/java/gdsc/skhu/liferary/domain/DTO/MainPostDTO.java
  src/main/java/gdsc/skhu/liferary/domain/Image.java
  src/main/java/gdsc/skhu/liferary/domain/MainPost.java
  src/main/java/gdsc/skhu/liferary/domain/Study.java
  src/main/java/gdsc/skhu/liferary/repository/ImageRepository.java
  src/main/java/gdsc/skhu/liferary/service/BoardPostService.java
  src/main/java/gdsc/skhu/liferary/service/FirebaseService.java
  src/main/java/gdsc/skhu/liferary/service/ImageService.java
  src/main/java/gdsc/skhu/liferary/service/MainPostService.java
  src/main/java/gdsc/skhu/liferary/util/StringListConverter.java
  src/main/resources/application.yml
  src/test/java/gdsc/skhu/liferary/service/BoardPostServiceTest.java
Labels: enhancement

#19 chore: edit test
  src/main/.DS_Store
  src/test/java/gdsc/skhu/liferary/service/BoardPostServiceTest.java
Labels: chore

#20 fix: fix build error
  src/main/java/gdsc/skhu/liferary/controller/MainPostController.java
  src/main/java/gdsc/skhu/liferary/domain/BoardPost.java
  src/main/java/gdsc/skhu/liferary/domain/Comment.java
Labels: fix

#21 fix: fix NullPointerException
  src/main/java/gdsc/skhu/liferary/util/StringListConverter.java
Labels: fix
